import type { Metadata } from 'next'
import { Noto_Sans_SC } from 'next/font/google'
import localFont from 'next/font/local'

import './globals.css'
import { Navigation } from '@/src/app/navigation'

const noto = Noto_Sans_SC({
  variable: '--font-noto',
  subsets: ['latin']
})
// Font files can be colocated inside of `app`
const unboundedSans = localFont({
  src: '../public/font/UnboundedSans.woff2',
  variable: '--font-unbound',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">

      <body className={`${noto.variable} ${unboundedSans.variable}`}>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
